[workspace]
resolver = "3"
members = ["crates/*"]
exclude = ["crates/worker", "crates/commander"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "LicenseRef-Proprietary"
authors = ["Ancient"]

[workspace.dependencies]
app = { path = "crates/app" }
agent = { path = "crates/agent" }
agent-ui = { path = "crates/agent-ui" }
action = { path = "crates/action" }
cognition = { path = "crates/cognition" }
perception = { path = "crates/perception" }
agent-error = { path = "crates/agent-error" }
agent-utils = { path = "crates/agent-utils" }
agent-llm = { path = "crates/agent-llm" }
agent-manager = { path = "crates/agent-manager" }
agent-session = { path = "crates/agent-session" }
serde_json = "1"
thiserror = "2"
tokio = { version = "1.50", features = ["rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
toolcraft-request = { version = "0.2.3"}
toolcraft-config = { version = "0.2.0" }
