[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
agent = { workspace = true }
agent-core = { package = "core", path = "../core" }
agent-error = { workspace = true }
agent-llm = { workspace = true }
agent-manager = { workspace = true }
agent-ui = { workspace = true }
agent-utils = { workspace = true }
cognition = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toolcraft-config = { workspace = true }
